version: '3'
services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TZ: Europe/Moscow
                USER_GROUP_ID: "${USER_GROUP_ID:-1000}"
                USER_ID: "${USER_ID:-1000}"
        container_name: ${APP_NAME}_app
        restart: unless-stopped
        tty: true
        environment:
            - SERVICE_TAGS=dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - internal
        depends_on:
            - pgsql
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        container_name: ${APP_NAME}_nginx
        environment:
            NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
            FASTCGI_PASS: "${APP_NAME}_app:9000"
        volumes:
            - ./:/var/www
            - ./docker/nginx/templates:/etc/nginx/templates
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - internal
            - web
        depends_on:
            - app
    pgsql:
        image: postgres
        restart: unless-stopped
        tty: true
        container_name: ${APP_NAME}_pgsql
        ports:
            - "${DB_PGSQL_EXT_PORT}:5432"
        environment:
            - TZ="Europe/Moscow"
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - internal
    redis:
        image: redis:latest
        container_name: ${APP_NAME}_redis
        ports:
            - "${REDIS_PORT}:6379"
        networks:
            - internal
networks:
    web:
        external: true
    internal:
        driver: bridge
volumes:
    pgdata:
        driver: local
